install:
  - ps: Install-Product node LTS $env:PLATFORM
  - npm config set msvs_version 2015 --global
  - npm install -g node-gyp
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
build: off
platform:
- x64
